"use client";
import Link from "next/link";import{useState}from"react";import{useRouter}from"next/navigation";
export function PropertyTeamAssignments({propertyId,assignments,eligibleMembers,canManage}:{propertyId:string;assignments:any[];eligibleMembers:any[];canManage:boolean}){
 const router=useRouter();const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function save(fd:FormData){setBusy(true);setError("");try{const r=await fetch(`/api/properties/${propertyId}/team`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({memberIds:fd.getAll("memberIds").map(String)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save assignments");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to save assignments")}finally{setBusy(false)}}
 const managers=assignments.filter(a=>a.member.role==="PROPERTY_MANAGER"),users=assignments.filter(a=>a.member.role==="USER");
 const eligibleManagers=eligibleMembers.filter(m=>m.role==="PROPERTY_MANAGER"),eligibleUsers=eligibleMembers.filter(m=>m.role==="USER"),assigned=new Set(assignments.map(a=>a.organizationMemberId));
 const list=(items:any[])=><div className="propertyAssignedList">{items.map(a=><div className="propertyAssignedPerson" key={a.id}><Link href={`/team/${a.member.id}`}><strong>{a.member.user.name||a.member.user.email}</strong></Link><small>{a.member.user.email}{a.member.mobilePhone?` · ${a.member.mobilePhone}`:""}</small></div>)}{!items.length&&<p className="muted">None assigned.</p>}</div>;
 const choices=(items:any[])=><div className="propertyAssignmentChecklist">{items.map(m=><label key={m.id} className="propertyAssignmentCheck"><input type="checkbox" name="memberIds" value={m.id} defaultChecked={assigned.has(m.id)} disabled={m.status!=="ACTIVE"}/><span><strong>{m.user.name||m.user.email}</strong><small>{m.user.email}{m.mobilePhone?` · ${m.mobilePhone}`:""}</small></span></label>)}{!items.length&&<p className="muted">No eligible members.</p>}</div>;
 return <div className="card"><h2 style={{marginTop:0}}>Team Assignments</h2><p className="muted">Property Managers and Users assigned to this Property.</p>
  <div className="propertyTeamColumns"><section><h3>Property Managers</h3>{list(managers)}</section><section><h3>Users</h3>{list(users)}</section></div>
  {canManage?<form action={save} className="propertyAssignmentManager"><h3>Manage Team Assignments</h3><p className="muted">Assignments are maintained by Admin and stay synchronized with Team Member Property Access.</p><div className="propertyTeamColumns"><section><h4>Property Managers</h4>{choices(eligibleManagers)}</section><section><h4>Users</h4>{choices(eligibleUsers)}</section></div>{error&&<p className="error">{error}</p>}<button className="button" disabled={busy} style={{marginTop:12}}>{busy?"Saving...":"Save Team Assignments"}</button></form>:<p className="muted">Property assignments are read-only for Property Managers.</p>}
 </div>;
}
