services:
  db:
    image: postgres:16-alpine
    container_name: edekhbhal-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edekhbhal
    ports:
      - "5432:5432"
    volumes:
      - edekhbhal_pgdata:/var/lib/postgresql/data

volumes:
  edekhbhal_pgdata:
