services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: edekhbhal
      POSTGRES_PASSWORD: edekhbhal
      POSTGRES_DB: edekhbhal
    ports:
      - "5432:5432"
    volumes:
      - edekhbhal_pg:/var/lib/postgresql/data
volumes:
  edekhbhal_pg:
