-- eDekhbhal v0.3.0 schema upgrade
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'PROFILE_UPDATED';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'PROPERTY_REACTIVATED';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'WORK_AREA_REACTIVATED';

ALTER TABLE "Property"
ADD COLUMN IF NOT EXISTS "status" "Status" NOT NULL DEFAULT 'ACTIVE';
