import React from "react";
import {ActivityIndicator,Pressable,StyleSheet,Text,View,ViewStyle} from "react-native";
export const colors={bg:"#f3f7f6",card:"#ffffff",text:"#13252a",muted:"#60767b",border:"#dbe8e5",primary:"#0d5b63",primaryDark:"#084951",success:"#e6f6ef",warning:"#fff6df",danger:"#b42318",soft:"#eaf5f3"};
export function ScreenHeader({organizationName,title,subtitle}:{organizationName?:string;title:string;subtitle?:string}){return <View style={styles.header}><View style={{flex:1}}><Text style={styles.org}>{organizationName||"eDekhbhal"}</Text><Text style={styles.title}>{title}</Text>{subtitle?<Text style={styles.subtitle}>{subtitle}</Text>:null}</View><View style={styles.brandBadge}><Text style={styles.brandBadgeText}>eD</Text></View></View>}
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle|ViewStyle[]}){return <View style={[styles.card,style]}>{children}</View>}
export function PrimaryButton({title,onPress,disabled,busy}:{title:string;onPress:()=>void;disabled?:boolean;busy?:boolean}){return <Pressable style={({pressed})=>[styles.primaryButton,(disabled||busy)&&styles.disabled,pressed&&!disabled&&{transform:[{scale:.99}]}]} onPress={onPress} disabled={disabled||busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryButtonText}>{title}</Text>}</Pressable>}
export function SecondaryButton({title,onPress,disabled}:{title:string;onPress:()=>void;disabled?:boolean}){return <Pressable style={({pressed})=>[styles.secondaryButton,disabled&&styles.disabled,pressed&&!disabled&&{backgroundColor:colors.soft}]} onPress={onPress} disabled={disabled}><Text style={styles.secondaryButtonText}>{title}</Text></Pressable>}
export function Pill({children}:{children:React.ReactNode}){return <View style={styles.pill}><Text style={styles.pillText}>{children}</Text></View>}
export const styles=StyleSheet.create({header:{backgroundColor:colors.bg,paddingHorizontal:20,paddingTop:12,paddingBottom:14,flexDirection:"row",alignItems:"center",gap:12},org:{fontSize:11,color:colors.primary,fontWeight:"900",letterSpacing:1.2,textTransform:"uppercase"},title:{fontSize:26,lineHeight:32,color:colors.text,fontWeight:"900",marginTop:4,letterSpacing:-.5},subtitle:{marginTop:4,color:colors.muted,fontSize:13,lineHeight:18},brandBadge:{width:46,height:46,borderRadius:15,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",shadowColor:"#0d5b63",shadowOpacity:.18,shadowRadius:10,shadowOffset:{width:0,height:5},elevation:4},brandBadgeText:{color:"white",fontWeight:"900",fontSize:18},card:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.border,borderRadius:20,padding:17,shadowColor:"#17373b",shadowOpacity:.04,shadowRadius:12,shadowOffset:{width:0,height:6},elevation:1},primaryButton:{minHeight:52,borderRadius:16,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",paddingHorizontal:18,paddingVertical:12},primaryButtonText:{color:"white",fontWeight:"900",fontSize:16},secondaryButton:{minHeight:48,borderRadius:16,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center",paddingHorizontal:16,paddingVertical:10,backgroundColor:"white"},secondaryButtonText:{color:colors.primary,fontWeight:"800"},disabled:{opacity:.45},pill:{alignSelf:"flex-start",backgroundColor:colors.soft,borderRadius:999,paddingHorizontal:11,paddingVertical:6},pillText:{color:colors.primaryDark,fontWeight:"800",fontSize:12}});
