import {test,expect} from "@playwright/test";
import {accountEmails,e2eSecret,login,mobileLogin,setupFixtures} from "./helpers";

async function reportedFixture(request:any){
 const setup=await setupFixtures(request);
 const r=await request.post("/api/e2e/reported-work",{headers:{"x-e2e-secret":e2eSecret()}});
 expect(r.ok(),await r.text()).toBeTruthy();
 return{...setup,...await r.json()};
}
function localStart(){const d=new Date(Date.now()+3600000),p=(n:number)=>String(n).padStart(2,"0");return`${d.getUTCFullYear()}-${p(d.getUTCMonth()+1)}-${p(d.getUTCDate())}T${p(d.getUTCHours())}:${p(d.getUTCMinutes())}`;}

test.describe("reported notes / work requests",()=>{
 test("Task Note creates unresolved Dashboard work for Admin",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user),note=`[E2E] task report ${Date.now()}`;const r=await request.post(`/api/mobile/occurrence-tasks/${f.occurrenceTaskA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note}});expect(r.ok(),await r.text()).toBeTruthy();const body=await r.json();expect(body.reportedWorkItemId).toBeTruthy();await login(page,accountEmails().admin);await page.goto("/dashboard");await expect(page.getByText(note)).toBeVisible();});
 test("Schedule Note is preserved in Reported Work report",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user),note=`[E2E] schedule report ${Date.now()}`;const r=await request.post(`/api/mobile/occurrences/${f.occurrenceA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note}});expect(r.ok(),await r.text()).toBeTruthy();await login(page,accountEmails().admin);await page.goto(`/reports/reported-work?search=${encodeURIComponent(note)}`);const row=page.locator("tbody tr").filter({hasText:note});await expect(row).toBeVisible();await expect(row.getByText("Schedule Note",{exact:true})).toBeVisible();});
 test("Property Manager dashboard excludes unassigned Property report",async({page,request})=>{const f=await reportedFixture(request);await login(page,accountEmails().pm);const r=await page.request.get("/api/dashboard/live");expect(r.ok(),await r.text()).toBeTruthy();const b=await r.json(),reported=b.attention.filter((x:any)=>x.kind==="REPORTED_WORK");expect(reported.every((x:any)=>x.propertyId===f.propertyA.id)).toBeTruthy();expect(reported.some((x:any)=>x.id===f.propertyBReportId)).toBeFalsy();});
 test("Dismiss removes Dashboard item but keeps report history",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user),note=`[E2E] dismiss ${Date.now()}`;const c=await request.post(`/api/mobile/occurrence-tasks/${f.occurrenceTaskA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note}}),created=await c.json();await login(page,accountEmails().admin);const d=await page.request.post(`/api/reported-work/${created.reportedWorkItemId}/dismiss`);expect(d.ok(),await d.text()).toBeTruthy();const live=await(await page.request.get("/api/dashboard/live")).json();expect(live.attention.some((x:any)=>x.id===created.reportedWorkItemId)).toBeFalsy();await page.goto(`/reports/reported-work?search=${encodeURIComponent(note)}`);await expect(page.getByText(note)).toBeVisible();await expect(page.getByText("DISMISSED",{exact:true})).toBeVisible();});
 test("Create Schedule from report defaults One Time",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user);const c=await request.post(`/api/mobile/occurrence-tasks/${f.occurrenceTaskA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note:`[E2E] default ${Date.now()}`}}),created=await c.json();await login(page,accountEmails().admin);await page.goto(`/schedules/new?workAreaId=${f.workAreaA.id}&reportedWorkItemId=${created.reportedWorkItemId}`);const oneTime=page.getByRole("button",{name:"One Time",exact:true});const recurring=page.getByRole("button",{name:"Recurring",exact:true});await expect(oneTime).toHaveClass(/\bactive\b/);await expect(recurring).not.toHaveClass(/\bactive\b/);await expect(page.getByLabel("End Date (optional)")).toHaveCount(0);});
 test("Dismissed item can later link to Schedule and retains dismissal",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user),note=`[E2E] later schedule ${Date.now()}`;const c=await request.post(`/api/mobile/occurrence-tasks/${f.occurrenceTaskA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note}}),created=await c.json();await login(page,accountEmails().admin);await page.request.post(`/api/reported-work/${created.reportedWorkItemId}/dismiss`);const s=await page.request.post("/api/schedules",{data:{name:`[E2E] follow-up ${Date.now()}`,frequencyType:"ONE_TIME",recurrenceUnit:null,recurrenceInterval:null,recurrenceConfig:null,startLocal:localStart(),endDate:null,timezone:"America/Denver",workAreaId:f.workAreaA.id,reportedWorkItemId:created.reportedWorkItemId,tasks:[{taskId:f.taskA.id,sequence:1,duration:"00:15",evidenceRule:"NONE",randomEveryN:null,randomEvidenceType:null}]}});expect(s.ok(),await s.text()).toBeTruthy();await page.goto(`/reports/reported-work?search=${encodeURIComponent(note)}`);const row=page.locator("tbody tr").filter({hasText:note});await expect(row).toBeVisible();await expect(row.getByText("SCHEDULE CREATED",{exact:true})).toBeVisible();await expect(row.getByText(/^Dismissed /)).toBeVisible();await expect(row.getByRole("link",{name:"View Schedule"})).toBeVisible();});
 test("User cannot dismiss a reported item",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user);const c=await request.post(`/api/mobile/occurrence-tasks/${f.occurrenceTaskA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note:`[E2E] user denied ${Date.now()}`}}),created=await c.json();await login(page,accountEmails().user);expect((await page.request.post(`/api/reported-work/${created.reportedWorkItemId}/dismiss`)).status()).toBe(403);});
 test("Property Manager cannot action unassigned Property report",async({page,request})=>{const f=await reportedFixture(request);await login(page,accountEmails().pm);expect((await page.request.post(`/api/reported-work/${f.propertyBReportId}/dismiss`)).status()).toBe(404);});
 test("Reported Work follow-up can be switched from One Time to Recurring",async({page,request})=>{const f=await reportedFixture(request),token=await mobileLogin(request,accountEmails().user);const c=await request.post(`/api/mobile/occurrence-tasks/${f.occurrenceTaskA.id}/notes`,{headers:{Authorization:`Bearer ${token}`},data:{note:`[E2E] recurring option ${Date.now()}`}}),created=await c.json();await login(page,accountEmails().admin);await page.goto(`/schedules/new?workAreaId=${f.workAreaA.id}&reportedWorkItemId=${created.reportedWorkItemId}`);const oneTime=page.getByRole("button",{name:"One Time",exact:true});const recurring=page.getByRole("button",{name:"Recurring",exact:true});await expect(oneTime).toHaveClass(/\bactive\b/);await recurring.click();await expect(recurring).toHaveClass(/\bactive\b/);await expect(oneTime).not.toHaveClass(/\bactive\b/);await expect(page.getByLabel("End Date (optional)")).toBeVisible();});
});
