import {expect,test} from "@playwright/test";
test("Demo explains planning and execution foundations safely",async({page})=>{
 await page.goto("/demo");
 await expect(page.getByText("WORK AREA + QR DEMO")).toBeVisible();
 await expect(page.getByText(/QR never grants authorization/)).toBeVisible();
 await expect(page.getByText("TASK MASTER DEMO")).toBeVisible();
 await expect(page.getByText("SCHEDULE MASTER DEMO")).toBeVisible();
 await expect(page.getByText("OCCURRENCE FOUNDATION DEMO")).toBeVisible();
 await expect(page.getByText(/nonexistent local clock time/i)).toBeVisible();
 await expect(page.getByText("MY WORK + SUPERSESSION DEMO")).toBeVisible();
 await expect(page.getByRole("heading",{name:"Claim safely, validate location, preserve history"})).toBeVisible();
 await expect(page.getByText(/eligible USER can claim open work without manager approval/i)).toBeVisible();
 await expect(page.getByText(/One per Organization Membership/i)).toBeVisible();
 await expect(page.getByText(/older due unstarted work becomes MISSED/i)).toBeVisible();
 await expect(page.getByText(/QR confirms the exact Work Area but never grants/i)).toBeVisible();
 await expect(page.getByText(/wrong Site, stale QR, cross-tenant work/i)).toBeVisible();
 await expect(page.getByText(/mismatched idempotent replays fail closed/i)).toBeVisible();
 await expect(page.getByText("TASK EXECUTION + COMPLETION DEMO")).toBeVisible();
 await expect(page.getByText(/Viewing Previous or Next Task content never/i)).toBeVisible();
 await expect(page.getByText(/evidence-required Task cannot complete until matching evidence metadata is VERIFIED/i)).toBeVisible();
 await expect(page.getByText("EVIDENCE CAPTURE FOUNDATION DEMO")).toBeVisible();
 await expect(page.getByText(/Successful upload records SHA-256 metadata but remains PENDING/i)).toBeVisible();
 await expect(page.getByText(/Public QR never exposes evidence/i)).toBeVisible();
 await expect(page.getByText(/expired intent, wrong object path, UPDATE\/DELETE, and public access fail closed/i)).toBeVisible();
 await expect(page.getByText("EVIDENCE VERIFICATION + NORMALIZATION DEMO")).toBeVisible();
 await expect(page.getByText(/Normal Web\/API runtime cannot claim or complete processing/i)).toBeVisible();
 await expect(page.getByText(/processing claim gets a short lease and claim token/i)).toBeVisible();
 await expect(page.getByText("EVIDENCE WORKER + AUTHORIZED READS DEMO")).toBeVisible();
 await expect(page.getByText(/worker capability role is NOLOGIN, non-BYPASSRLS/i)).toBeVisible();
 await expect(page.getByText(/signed URL, capped at 60 seconds/i)).toBeVisible();
 await expect(page.getByText("EVIDENCE WORKER TRANSPORT 03B1 DEMO")).toBeVisible();
 await expect(page.getByText(/separate Node 22 container/i)).toBeVisible();
 await expect(page.getByText(/dedicated Supabase Auth machine account has no app_user or Organization Membership/i)).toBeVisible();
 await expect(page.getByText(/No service-role key, JWT signing secret, or S3 static credential/i)).toBeVisible();
});
