import {expect,test} from "@playwright/test";
test("Demo explains planning and execution foundations safely",async({page})=>{
 await page.goto("/demo");
 await expect(page.getByText("WORK AREA + QR DEMO")).toBeVisible();
 await expect(page.getByText(/QR never grants authorization/)).toBeVisible();
 await expect(page.getByText("TASK MASTER DEMO")).toBeVisible();
 await expect(page.getByText("SCHEDULE MASTER DEMO")).toBeVisible();
 await expect(page.getByText("OCCURRENCE FOUNDATION DEMO")).toBeVisible();
 await expect(page.getByText(/nonexistent local clock time/i)).toBeVisible();
 await expect(page.getByText("MY WORK + SUPERSESSION DEMO")).toBeVisible();
 await expect(page.getByRole("heading",{name:"Claim safely, validate location, preserve history"})).toBeVisible();
 await expect(page.getByText(/eligible USER can claim open work without manager approval/i)).toBeVisible();
 await expect(page.getByText(/One per Organization Membership/i)).toBeVisible();
 await expect(page.getByText(/older due unstarted work becomes MISSED/i)).toBeVisible();
 await expect(page.getByText(/QR confirms the exact Work Area but never grants/i)).toBeVisible();
 await expect(page.getByText(/wrong Site, stale QR, cross-tenant work/i)).toBeVisible();
 await expect(page.getByText(/mismatched idempotent replays fail closed/i)).toBeVisible();
 await expect(page.getByText("TASK EXECUTION + COMPLETION DEMO")).toBeVisible();
 await expect(page.getByText(/Viewing Previous or Next Task content never/i)).toBeVisible();
 await expect(page.getByText(/evidence-required Task cannot complete until matching evidence metadata is VERIFIED/i)).toBeVisible();
});
