import {test,expect} from "@playwright/test";
import {accountEmails,login,setupFixtures} from "./helpers";

test.describe("cumulative fine-tuning UI",()=>{
 test("Dashboard uses consolidated summary and top Recent Evidence controls",async({page,request})=>{await setupFixtures(request);await login(page,accountEmails().admin);await page.goto("/dashboard");await expect(page.getByRole("heading",{name:"Today at a glance"})).toBeVisible();await expect(page.getByRole("heading",{name:"Latest photos & videos"})).toBeVisible();await expect(page.getByRole("button",{name:"Maximize evidence"})).toBeVisible();await expect(page.getByText("Users Online",{exact:true})).toHaveCount(0);});
 test("Audit exposes entity dropdowns and selectable page size",async({page,request})=>{await setupFixtures(request);await login(page,accountEmails().admin);await page.goto("/audit");await expect(page.getByLabel("Entity Type",{exact:true})).toBeVisible();await expect(page.getByLabel("Entity ID",{exact:true})).toBeVisible();await expect(page.getByLabel("Rows / Page",{exact:true})).toHaveValue("50");await page.getByLabel("Rows / Page",{exact:true}).selectOption("25");await page.getByRole("button",{name:"Apply Filters"}).click();await expect(page).toHaveURL(/pageSize=25/);});
 test("Property Team Assignments keeps role-separated Admin controls",async({page,request})=>{const f=await setupFixtures(request);await login(page,accountEmails().admin);await page.goto(`/properties/${f.propertyA.id}?tab=team`);await expect(page.getByRole("heading",{name:"Team Assignments",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Property Managers",exact:true}).first()).toBeVisible();await expect(page.getByRole("heading",{name:"Users",exact:true}).first()).toBeVisible();await expect(page.getByRole("heading",{name:"Manage Team Assignments",exact:true})).toBeVisible();});
 test("Reports exposes Reported Notes / Work Requests",async({page,request})=>{await setupFixtures(request);await login(page,accountEmails().admin);await page.goto("/reports");await expect(page.getByRole("heading",{name:"Reported Notes / Work Requests"})).toBeVisible();await expect(page.getByRole("link",{name:"Open Reported Work"})).toBeVisible();});
});
