"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Member = { id:string; userId:string; role:"ADMIN"|"PROPERTY_MANAGER"|"USER"; status:string; user:{email:string;name:string|null} };
export function TeamManager({members,canManage,currentUserId}:{members:Member[];canManage:boolean;currentUserId:string}){
  const router=useRouter(); const [error,setError]=useState("");
  async function invite(fd:FormData){setError("");const r=await fetch("/api/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:String(fd.get("email")||""),role:String(fd.get("role")||"USER")})});const d=await r.json();if(!r.ok)setError(d.error||"Unable to add user");else router.refresh()}
  async function update(id:string,payload:object){setError("");const r=await fetch(`/api/team/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)setError(d.error||"Unable to update user");else router.refresh()}
  return <>{canManage&&<div className="card" style={{marginBottom:20}}><h2>Add / Invite User</h2><form action={invite} className="row responsiveRow"><input name="email" type="email" required placeholder="user@example.com"/><select name="role" defaultValue="USER"><option value="USER">User</option><option value="PROPERTY_MANAGER">Property Manager</option><option value="ADMIN">Admin</option></select><button className="button">Add User</button></form><p className="muted">Email sending is not connected yet. The invited user can use Login with the same email address.</p></div>}{error&&<p className="error">{error}</p>}<div className="card"><table className="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><strong>{m.user.name||m.user.email}</strong><br/><span className="muted">{m.user.email}</span></td><td>{m.role}</td><td>{m.status}</td><td>{canManage&&m.userId!==currentUserId?<div className="row compact"><select value={m.role} onChange={e=>update(m.id,{role:e.target.value})}><option value="USER">User</option><option value="PROPERTY_MANAGER">Property Manager</option><option value="ADMIN">Admin</option></select><button className="button small secondary" onClick={()=>update(m.id,{status:m.status==="ACTIVE"?"INACTIVE":"ACTIVE"})}>{m.status==="ACTIVE"?"Inactivate":"Reactivate"}</button></div>:m.userId===currentUserId?<span className="muted">Current user</span>:null}</td></tr>)}</tbody></table></div></>;
}
