"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type WorkArea = { id:string; name:string; description:string|null; locationIdentifier:string|null; status:string; qrCodes:{id:string;tokenPreview:string;generatedAt:string|Date}[] };
type Props = { propertyId:string; propertyName:string; workAreas:WorkArea[]; canManage:boolean; propertyActive:boolean };

export function WorkAreaManager({ propertyId, propertyName, workAreas, canManage, propertyActive }: Props) {
  const router=useRouter();
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<WorkArea|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const [qr,setQr]=useState<{workAreaName:string;qrId:string;dataUrl:string}|null>(null);

  async function createWorkArea(fd:FormData){setSaving(true);setError("");const payload={propertyId,name:String(fd.get("name")||""),description:String(fd.get("description")||""),locationIdentifier:String(fd.get("locationIdentifier")||"")};try{const r=await fetch("/api/work-areas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create Work Area");setOpen(false);setQr({workAreaName:payload.name,qrId:d.qr.id,dataUrl:d.qr.dataUrl});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to create Work Area")}finally{setSaving(false)}}
  async function patch(id:string,payload:any){setSaving(true);setError("");try{const r=await fetch(`/api/work-areas/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to update Work Area");setEditing(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to update Work Area")}finally{setSaving(false)}}
  async function qrAction(id:string,name:string,action:"reprint"|"regenerate"){setError("");try{const r=await fetch(`/api/work-areas/${id}/qr/${action}`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||`Unable to ${action} QR code`);setQr({workAreaName:name,qrId:d.qr.id,dataUrl:d.qr.dataUrl});router.refresh()}catch(e){setError(e instanceof Error?e.message:`Unable to ${action} QR code`)}}
  function printQr(){if(!qr)return;const w=window.open("","_blank","width=700,height=800");if(!w)return;w.document.write(`<html><head><title>${qr.workAreaName} QR</title><style>body{font-family:Arial;text-align:center;padding:40px}img{width:420px;height:420px}.id{font-family:monospace;color:#555}</style></head><body><h1>eDekhbhal</h1><h2>${qr.workAreaName}</h2><p>Property: ${propertyName}</p><img src="${qr.dataUrl}"/><p class="id">QR ID: ${qr.qrId}</p></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}

  return <><div className="row"><div style={{marginRight:"auto"}}><h2>Work Areas</h2><p className="muted">Parent Property: <strong>{propertyName}</strong></p></div>{canManage&&propertyActive&&<button className="button" onClick={()=>setOpen(true)}>Add Work Area</button>}</div>{!propertyActive&&<p className="error">This Property is inactive. Reactivate it before creating new Work Areas.</p>}{error&&<p className="error">{error}</p>}<div className="card"><table className="table"><thead><tr><th>Name</th><th>Parent Property</th><th>Description</th><th>Location</th><th>Status</th><th>QR</th><th>Actions</th></tr></thead><tbody>{workAreas.map(wa=>{const active=wa.qrCodes[0];return <tr key={wa.id}><td><strong>{wa.name}</strong></td><td>{propertyName}</td><td>{wa.description||"—"}</td><td>{wa.locationIdentifier||"—"}</td><td>{wa.status}</td><td>{active?active.tokenPreview:"No active QR"}</td><td>{canManage&&<div className="row compact"><button className="button small secondary" onClick={()=>setEditing(wa)}>View / Edit</button><button className="button small secondary" onClick={()=>patch(wa.id,{status:wa.status==="ACTIVE"?"INACTIVE":"ACTIVE"})}>{wa.status==="ACTIVE"?"Inactivate":"Reactivate"}</button>{wa.status==="ACTIVE"&&<><button className="button small secondary" onClick={()=>qrAction(wa.id,wa.name,"reprint")}>Reprint</button><button className="button small danger" onClick={()=>qrAction(wa.id,wa.name,"regenerate")}>Regenerate</button></>}</div>}</td></tr>})}{!workAreas.length&&<tr><td colSpan={7} className="muted">No Work Areas yet.</td></tr>}</tbody></table></div>
  {open&&<div className="modalBackdrop"><div className="modal"><h2>Add Work Area</h2><p><strong>Parent Property:</strong> {propertyName}</p><form action={createWorkArea}><label>Work Area Name<input name="name" required minLength={2}/></label><label>Description<textarea name="description" rows={3}/></label><label>Exact Location Identifier<input name="locationIdentifier" placeholder="2nd Floor, East Wing, Room 204"/></label><div className="row"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button" disabled={saving}>{saving?"Creating...":"Create Work Area & QR"}</button></div></form></div></div>}
  {editing&&<div className="modalBackdrop"><div className="modal"><h2>View / Edit Work Area</h2><p><strong>Parent Property:</strong> {propertyName}</p><form action={fd=>patch(editing.id,{name:String(fd.get("name")||""),description:String(fd.get("description")||""),locationIdentifier:String(fd.get("locationIdentifier")||"")})}><label>Name<input name="name" defaultValue={editing.name}/></label><label>Description<textarea name="description" defaultValue={editing.description||""}/></label><label>Exact Location Identifier<input name="locationIdentifier" defaultValue={editing.locationIdentifier||""}/></label><div className="row"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="button" disabled={saving}>Save Work Area</button></div></form></div></div>}
  {qr&&<div className="modalBackdrop"><div className="modal qrModal"><h2>{qr.workAreaName}</h2><p className="muted">Property: {propertyName}</p><img className="qrImage" src={qr.dataUrl} alt={`QR for ${qr.workAreaName}`}/><p className="mono">QR ID: {qr.qrId}</p><div className="row"><button className="button secondary" onClick={()=>setQr(null)}>Close</button><button className="button" onClick={printQr}>Print QR</button></div></div></div>}</>;
}
